### ISSUE TITLE
Some Readme Issues.

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk-old#11]
The following are a few issues that occurred to me while parsing the Readme as a fresh starter.

- 

 > Clone bitcoindevkit/murmel to directory ../murmel relative to the ./bdk project repo.

This line felt a little confusing. Maybe change it to something like 
>Clone bitcoindevkit/murmel in the same directory with bdk folder. 

Or better give explicit command-line instructions. 

- 

 > Install Android Studio and NDK

>
>Open Android Studio -> SDK Manager
>Select SDK Tools tab Install "NDK (Side by side)"

This can be simplified as
>Open Android Studio -> Tools -> SDK Manager -> SDK Tools -> install "NDK (Side by side)"

 

- 
There should be a `cargo build` and `cargo test` instruction at the end.

- 
Currently, the Regtest Box in bitcoindevkit/bitcoin-regtest-box compiles bitcoin core. I don't see how the user can test bdk with it. Maybe something for the future, but a newcomer can spend unnecessary time there which doesn't relate to bdk as of now.

- 
Also, the dependency list felt too high for my comfort level. I understand its probably because of all the android stuffs, but generally, in Bitcoin, it's preferred to keep dependencies as low as possible. Is that something this repo will work towards in the future, or it will adopt different philosophy?

**Comment by notmandatory** [comment]
Good suggestion to just put the command line steps for the murmel setup, something like: 
From bdk top level directory:
``` 
mkdir ../murmel
cd ../murmel
git clone git@github.com:bitcoindevkit/murmel.git
```

Agree also with simplifying the android studio tools line and adding steps to build and test the lib.

I've started a small CLI wallet example for manual testing and that's where I started putting instructions for using the regtest setup. It's very new but functional.. so I'll spend some time and flesh out those instructions in the examples/wallet/README.md file.

**Comment by thunderbiscuit** [comment]
Getting through the README myself right now.

Couldn't find the way to install the NDK as per the instructions (I have Android Studio 4.0 on OSX). The drop down menu `Tools` does not have the `SDK Manager` option, nor could I find it anywhere in any of the drop down menus. Instead I found it under preferences as per [this page](https://developer.android.com/studio/intro/update#sdk-manager).

So for me anyway, the process looked more like this:

Open Android Studio -> Preferences -> Appearance & Behavior -> System Settings -> Android SDK -> SDK Tools Tab -> Check the NDK (Side by side) box.

**Comment by thunderbiscuit** [comment]
Other small comments: 

1. A rough idea of the disk space needed for the full bdk setup would be nice to have at the beginning of the readme. I think the `ndk` is about 3.8GB on my machine. I don't know if the other Rust stuff is heavy, but overall it would be a nice touch to let devs know what they're in for. _Edit: finished building for the Android targets and my bdk repo is now 1.2GB. Not too bad. Is that pretty much everything though? Or is there much else I haven't seen? In any case, looks to be about 5GB max for `ndk` and `bdk` together, + `nigiri` (haven't installed it yet but will report back)._

2. Step 6 of the Setup section mentions setting environment variables, a step which would become obsolete upon a fix to cargo-ndk being merged. The fix appears to have been merged, so am I right in thinking that this step could now be taken off the readme?

**Comment by rajarshimaitra** [comment]
@thunderBiscuit those are valid issues. It's also unclear to me why we need Android Studio and NDK in the first place. At least in this stage of the project.

**Comment by notmandatory** [comment]
closing issue due to move to `magical-bitcoin-wallet` based code for `bdk`
