### ISSUE TITLE
env_logger dependency not installed for `bdk_cli` example

### ISSUE THREAD

**Issue by justinmoon** [bitcoindevkit/bdk-old#4]
It's marked as "optional" in `Cargo.toml`. Perhaps you could create a "simple_logger" feature and enable it [like this](https://github.com/MagicalBitcoin/magical-bitcoin-wallet/blob/master/Cargo.toml#L54)?

**Comment by notmandatory** [comment]
Hi sorry for the long delay. I renamed the bdk_cli to examples/wallet and added the env_logger to dev-dependencies to fix the logging issue. Let me know if that works OK.

**Comment by notmandatory** [comment]
closing issue due to move to `magical-bitcoin-wallet` based code for `bdk`
