### ISSUE TITLE
Must restart example wallet to sync and show balance 

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-old#45]
version: commit 3d695d09788f66e5b0b7c482ad838e44aa5f8de4 

Wallet balance is not always shown and wallet.log not created when starting a fresh `regtest` wallet. I had this happen once, but then not happen on a second test. 

steps to reproduce:

1. start with no prior data
   ```
   $ nigiri stop
   $ rm -rf regtest
   $ nigiri start
   ```
2. start example wallet in regtest mode and send regtest coins to it's deposit address
   ```
   $ cargo run --example wallet -- -n regtest -p testpass -a 127.0.0.1:18432 
   ``` 
   note: no regtest/wallet.log file greated
   ```
   $ docker exec -it resources_bitcoin_1 bitcoin-cli -regtest -rpcport=19001 -rpcuser=admin1 -rpcpassword=123 generatetoaddress 100 2NCks2FrsbaEbovz7YUYttFVc94SYpgwat7
   ```
3. check wallet balance and is 0
   ```
   >> balance 
   balance: 0, confirmed: 0
   >> stop
   ```
4. restart wallet and balance is displayed, also regtest/wallet.log is created
   ```
   >> balance
   balance: 246250000000, confirmed: 246250000000
   >> 
   ```

**Comment by thunderbiscuit** [comment]
I was able to reproduce bug and solution with `bitcoin-regtest-box`. Same thing. Restarting the wallet fixed it. 

Any subsequent transactions show up fine.

**Comment by notmandatory** [comment]
closing issue due to move to `magical-bitcoin-wallet` based code for `bdk`
