### ISSUE TITLE
Compile error in tests with`cargo test --features java`

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk-old#8]
There is a compilation error while performing `api` tests
```
error: cannot find macro `debug` in this scope
   --> src/api.rs:369:13
    |
369 |             debug!("start 2 returned")
    |             ^^^^^

```
Which is easily solvable. `log::debug` is not imported in `api` tests. Will open a PR with a fix.

**Comment by notmandatory** [comment]
this should be fixed now, give it a try and if it's OK lets close this one too.

**Comment by rajarshimaitra** [comment]
Fix ACK.
